server:
  port: ${APP_PORT:0}

app:
  base-url: /v1/oscar
  first-service:
    base-url:
      movies: ${FIRST_SERVICE_URL}/movies
logging:
  level:
    root: info

spring:
  datasource:
    url: jdbc:h2:mem:default
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 15