server:
  port: ${APP_PORT:8090}

app:
  base-url: /v1/oscar
  first-service:
    base-url:
      movies: ${FIRST_SERVICE_URL:http://localhost:8080/lab2-1.0-SNAPSHOT/api}/movies
logging:
  level:
    root: info

spring:
  datasource:
    url: jdbc:h2:mem:default
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true